version: '3.7'
services:
  laravel-db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: Igss.2021
      MYSQL_DATABASE: sicma_dev
      MYSQL_USER: usr_laravel
      MYSQL_PAASWORD: usr.igss.2021
    ports: 
      - 33069:3306
    volumes: 
      - ./database/schemas/:/var/lib/mysql
    networks:
      laravel_net:
        ipv4_address: 172.21.100.9
  laravel_prod:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 8200:80
    volumes: 
      - ./sicma:/var/www/
      - ./sicma/public:/var/www/html
    networks: 
      laravel_net:
        ipv4_address: 172.21.100.10
    depends_on: 
      - laravel-db
  volumes: 
    sicma:
    database:
  networks: 
    laravel_net:
      driver: bridge
      ipam: 
        driver: default
        config: 
          - 
            subnet: 172.21.100.0/24





