version: '3.7'
services:
 sicma-prueba:
  build:
   context: ./
   dockerfile: Dockerfile 
  ports: 
   - 8600:80
  volumes: 
   - ./code-prueba:/var/www
   - ./code-prueba/public:/var/www/html
  networks: 
   laravel_prod_net:
    ipv4_address: 179.28.100.12
volumes: 
 code-prueba:
networks: 
 laravel_prod_net:
  driver: bridge
  ipam: 
   driver: default
   config: 
    - 
     subnet: 179.28.100.0/24 
